name: CD Backend
on:
  workflow_run:
    workflows: ["Backend CI"]  # Name of the CI workflow which trigger this pipeline
    types:
      - completed
 # push:
 #   branches:
 #     - main
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up kubeconfig
        run: | 
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      - name: Setup Helm
        uses: azure/setup-helm@v3
      - name: Deploy backend via Helm
        run: |
          helm upgrade --install backend ./helm-charts/backend/backend --namespace default --create-namespace
