name: ENV variable
on: 
env:
  WF_ENV: Available to all jobs
  wf_env: ${{ secret.job_ok }}
  Secret_env: ${{ secrets.GITHUB_TOKEN }}  # we can pass the token from here

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to only this job
    steps:
      - name: Log env variables
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
  log-default:
    runs-on: ubuntu-latest
    steps:
      - name: default
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
