name: testing via udemy

on: 
  schedule:
   # - cron: "0  * * * *"
  push:
    branches:
      - main
  

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python
        run: |
          import platform
          print (platform.processor())
        shell: python
  run-win-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: directory powershell
        run: get-location
      - name: directory bash
        run: pwd
        shell: bash
  run-github-action:
    runs-on: ubuntu-latest
    steps:
     #- name: java action
       #id: greet
       #uses: actions/hello-world-javascript-action@v1
       #with:
       #  who-to-greet: Rohit
     - name: log greeting time
       run: echo "$ {{ steps.greet.outputs.time }}"
     - name: checkout
       uses: actions/checkout@v1
     - name: list files
       run: |
         pwd
         ls -a
       

       
    
  

